<a href="https://colab.research.google.com/github/gautami06647/AI-ML-internship-assignments/blob/NLP-Projects/NLP_NLTK_Tokenization_Steaming.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

data = {
    "review": [
        "I loved this movie, the acting was amazing and story was great",
        "This movie was terrible, boring plot and poor acting",
        "An excellent film with strong performances",
        "Worst movie I have ever watched",
        "The movie was good but could have been better",
        "Amazing direction and beautiful cinematography",
        "Not worth watching at all",
        "The story was engaging and emotional",
        "Bad movie with weak storyline",
        "Fantastic movie, I enjoyed every moment"
    ] * 200   # creates 2000 rows
}

df = pd.DataFrame(data)
print("Total rows in dataset:", len(df))
df.head()

Total rows in dataset: 2000

                                              review
0  I loved this movie, the acting was amazing and...
1  This movie was terrible, boring plot and poor ...
2         An excellent film with strong performances
3                    Worst movie I have ever watched
4      The movie was good but could have been better

In [ ]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
from nltk.tokenize import word_tokenize

df["tokens"] = df["review"].apply(word_tokenize)
df.head()

,review,tokens
0,"I loved this movie, the acting was amazing and...","[I, loved, this, movie, ,, the, acting, was, a..."
1,"This movie was terrible, boring plot and poor ...","[This, movie, was, terrible, ,, boring, plot, ..."
2,An excellent film with strong performances,"[An, excellent, film, with, strong, performances]"
3,Worst movie I have ever watched,"[Worst, movie, I, have, ever, watched]"
4,The movie was good but could have been better,"[The, movie, was, good, but, could, have, been..."

In [ ]:
from nltk.stem import PorterStemmer

ps = PorterStemmer()

df["stemmed_words"] = df["tokens"].apply(
    lambda words: [ps.stem(w) for w in words]
)

df.head()

,review,tokens,stemmed_words
0,"I loved this movie, the acting was amazing and...","[I, loved, this, movie, ,, the, acting, was, a...","[i, love, thi, movi, ,, the, act, wa, amaz, an..."
1,"This movie was terrible, boring plot and poor ...","[This, movie, was, terrible, ,, boring, plot, ...","[thi, movi, wa, terribl, ,, bore, plot, and, p..."
2,An excellent film with strong performances,"[An, excellent, film, with, strong, performances]","[an, excel, film, with, strong, perform]"
3,Worst movie I have ever watched,"[Worst, movie, I, have, ever, watched]","[worst, movi, i, have, ever, watch]"
4,The movie was good but could have been better,"[The, movie, was, good, but, could, have, been...","[the, movi, wa, good, but, could, have, been, ..."

In [ ]:
for i in range(3):
    print("Original Review:")
    print(df["review"][i])
    print("\nTokens:")
    print(df["tokens"][i])
    print("\nStemmed Words:")
    print(df["stemmed_words"][i])
    print("-" * 60)

Original Review:
I loved this movie, the acting was amazing and story was great

Tokens:
['I', 'loved', 'this', 'movie', ',', 'the', 'acting', 'was', 'amazing', 'and', 'story', 'was', 'great']

Stemmed Words:
['i', 'love', 'thi', 'movi', ',', 'the', 'act', 'wa', 'amaz', 'and', 'stori', 'wa', 'great']
------------------------------------------------------------
Original Review:
This movie was terrible, boring plot and poor acting

Tokens:
['This', 'movie', 'was', 'terrible', ',', 'boring', 'plot', 'and', 'poor', 'acting']

Stemmed Words:
['thi', 'movi', 'wa', 'terribl', ',', 'bore', 'plot', 'and', 'poor', 'act']
------------------------------------------------------------
Original Review:
An excellent film with strong performances

Tokens:
['An', 'excellent', 'film', 'with', 'strong', 'performances']

Stemmed Words:
['an', 'excel', 'film', 'with', 'strong', 'perform']
------------------------------------------------------------